=== francescadonofrio/progetti-universitari/fdnails3/xml/catalogo.dtd
<!ELEMENT catalogo (smalto+)>

<!ELEMENT smalto (nome, descrizione, prezzo, immagine)>
<!ATTLIST smalto id ID #REQUIRED>

<!ELEMENT nome (#PCDATA)>
<!ELEMENT descrizione (#PCDATA)>
<!ELEMENT prezzo (#PCDATA)>
<!ELEMENT immagine (#PCDATA)>

=== francescadonofrio/progetti-universitari/fdnails3/xml/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "catalogo.dtd">
<catalogo>
  <smalto id="S01">
    <nome>Rosso Federica</nome>
    <descrizione>Rosso pieno - lucido</descrizione>
    <prezzo>8.90</prezzo>
    <immagine>red.jpg</immagine>
  </smalto>
  <smalto id="S02">
    <nome>Nude</nome>
    <descrizione>Nude chiaro - coprenza media</descrizione>
    <prezzo>9.50</prezzo>
    <immagine>nude.jpg</immagine>
  </smalto>
  <smalto id="S03">
    <nome>Nero</nome>
    <descrizione>Scuro - lucido</descrizione>
    <prezzo>9.90</prezzo>
    <immagine>black.jpg</immagine>
  </smalto>
  <smalto id="S04">
    <nome>Rosso Roberta</nome>
    <descrizione>ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao 


ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao ciao 
ciao ciao ciao ciao ciao ciao ciao 

ciao ciao ciao ciao ciao ciao ciao </descrizione>
    <prezzo>9.00</prezzo>
    <immagine>red.jpg</immagine>
  </smalto>
</catalogo>
