=== francescadonofrio/progetti-universitari/fdnails3/xml/promozioni.dtd
<!ELEMENT promozioni (sconti, bonus)>

<!ELEMENT sconti (sconto*)>
<!ELEMENT sconto (descrizione, applicazione)>
<!ATTLIST sconto id ID #REQUIRED
                tipo (generico|registrati|prodotto|personalizzato) #REQUIRED
                valorePercento CDATA #REQUIRED
                dal CDATA #REQUIRED
                al CDATA #REQUIRED>

<!ELEMENT bonus (bonusterm*)>
<!ELEMENT bonusterm (descrizione, applicazione)>
<!ATTLIST bonusterm id ID #REQUIRED
                    tipo (generico|personalizzato) #REQUIRED
                    crediti CDATA #REQUIRED
                    dal CDATA #REQUIRED
                    al CDATA #REQUIRED>

<!ELEMENT descrizione (#PCDATA)>

<!ELEMENT applicazione (tutti | criterio | idProdotto)>
<!ELEMENT tutti EMPTY>

<!ELEMENT criterio EMPTY>
<!ATTLIST criterio tipo (reputazione|anzianita|crediti_spesi) #REQUIRED
                 valore CDATA #REQUIRED>

<!ELEMENT idProdotto (#PCDATA)>

=== francescadonofrio/progetti-universitari/fdnails3/xml/promozioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE promozioni SYSTEM "promozioni.dtd">
<promozioni>
  <sconti>
    <sconto id="SC01" tipo="prodotto" valorePercento="20%" dal="2026-03-11" al="2026-03-20">
      <descrizione>saldi di primavera</descrizione>
      <applicazione>
        <idProdotto>S01</idProdotto>
      </applicazione>
    </sconto>
  </sconti>
  <bonus>
    <bonusterm id="BO01" tipo="personalizzato" crediti="1" dal="2026-03-11" al="2026-03-20">
      <descrizione>1 credito per ogni acquisto effettuato</descrizione>
      <applicazione>
        <criterio tipo="reputazione" valore="1"/>
      </applicazione>
    </bonusterm>
  </bonus>
</promozioni>
